const fs = require("fs");
const fsp = require("fs/promises");
const path = require("path");
const PDFDocument = require("pdfkit");
const env = require("../config/env");

async function ensurePdfDirectory() {
  await fsp.mkdir(env.pdfStorageDir, { recursive: true });
}

function createSafeFileName(value) {
  return String(value).replace(/[^a-zA-Z0-9-_]/g, "_");
}

async function generateDepartmentPdf(order, department) {
  await ensurePdfDirectory();

  const fileName = `${createSafeFileName(order.order_number)}_${department}_${Date.now()}.pdf`;
  const absolutePath = path.join(env.pdfStorageDir, fileName);

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(absolutePath);
    doc.pipe(stream);

    doc.fontSize(16).text("Order Management Automation", { underline: true });
    doc.moveDown();
    doc.fontSize(12).text(`Department: ${department}`);
    doc.text(`Order Number: ${order.order_number}`);
    doc.text(`Shopify Order ID: ${order.order_id}`);
    doc.text(`Customer: ${order.customer_name || "N/A"}`);
    doc.text(`Delivery Date: ${order.delivery_date || "N/A"}`);
    doc.text(`Delivery Time: ${order.delivery_time || "N/A"}`);
    doc.text(`Specific Delivery Time: ${order.specific_delivery_time || "N/A"}`);
    doc.text(`Shipping Method: ${order.shipping_method || "N/A"}`);
    doc.moveDown();
    doc.text("This PDF is generated by backend automation.", { oblique: true });
    doc.end();

    stream.on("finish", resolve);
    stream.on("error", reject);
    doc.on("error", reject);
  });

  const relativePath = path.relative(process.cwd(), absolutePath);
  return {
    absolutePath,
    relativePath,
  };
}

module.exports = {
  generateDepartmentPdf,
};
