const DEPARTMENT_STATUS = Object.freeze({
  NA: "NA",
  PENDING: "PENDING",
  IN_PROGRESS: "IN-PROGRESS",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
});

const STATUS_COLOR_MAP = Object.freeze({
  [DEPARTMENT_STATUS.NA]: "Grey",
  [DEPARTMENT_STATUS.PENDING]: "Orange",
  [DEPARTMENT_STATUS.IN_PROGRESS]: "Blue",
  [DEPARTMENT_STATUS.SUCCESS]: "Green",
  [DEPARTMENT_STATUS.FAILED]: "Red",
});

const PRINT_JOB_STATUS = Object.freeze({
  PENDING: "PENDING",
  IN_PROGRESS: "IN-PROGRESS",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
});

module.exports = {
  DEPARTMENT_STATUS,
  STATUS_COLOR_MAP,
  PRINT_JOB_STATUS,
};
